# Generated by Django 4.1.7 on 2023-03-30 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('14964f50-e271-4ed0-869a-fe6028bbcc7c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('14964f50-e271-4ed0-869a-fe6028bbcc7c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('14964f50-e271-4ed0-869a-fe6028bbcc7c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('14964f50-e271-4ed0-869a-fe6028bbcc7c'), primary_key=True, serialize=False),
        ),
    ]
